language: python
python:
  - "3.8"
addons:
  postgresql: "10"
  firefox: "72.0"
  apt:
    packages:
      - postgresql-10
      - postgresql-10-postgis-2.5
services:
  - xvfb
before_install: 
  - wget -q -N https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux32.tar.gz
  - tar -xzf geckodriver-v0.29.0-linux32.tar.gz --directory /home/travis/bin
  # Needed for GDAL 2.2.2, which is needed for Django 3 - default libgdal-dev is version 1.1
  - sudo add-apt-repository -y ppa:ubuntugis/ppa 
  - sudo apt-get -y update
  - sudo apt-get -y install libgdal-dev
env:
  - DJANGO=2.2
install:
  - pip install --upgrade pip
  - pip install --use-deprecated=legacy-resolver -r requirements/travis-ci.txt
before_script:
  - psql -c 'ALTER ROLE travis SUPERUSER;' -U postgres
  - export DATABASE_URL="postgis://travis:@127.0.0.1:5432/stoqs"
script:  
  - export GEOS_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgeos_c.so
  - export GDAL_LIBRARY_PATH=/usr/lib/libgdal.so
  - ./test.sh CHANGEME load noextraload
after_script:
  - coveralls --base_dir stoqs
notifications:
  email:
    on_success: change
    on_failure: always
