version: '2'

volumes:
    static-files:
    media-files:

services:

  postgis:
    image: mbari/stoqs-postgis
    build:
        context: .
        dockerfile: Dockerfile-postgis
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
      - ${POSTGRES_WALDIR}:/var/lib/postgresql/waldir
      - ./postgres-stoqs.conf:/etc/postgresql.conf
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "${STOQS_PGHOST_PORT}:5432"
    # Set user for deployment on MacOS, assign HOST_ID=<result of `id -u`> in your .env file
    user: ${HOST_UID}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - STOQSADM_PASSWORD=${STOQSADM_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_INITDB_WALDIR=/var/lib/postgresql/waldir
    container_name: stoqs-postgis
    env_file:
      - ./.env

  mapserver:
    image: geodata/mapserver:7.0.1
    volumes:
      - ${STOQS_VOLS_DIR}/maps:/maps:ro
    container_name: stoqs-mapserver
    # Expose port 80 if PRODUCTION=false
    ##ports:
    ##  - "80:80"
    env_file:
      - ./.env

  stoqs:
    image: mbari/stoqs
    build:
        context: .
        dockerfile: Dockerfile-stoqs
    volumes:
      - ${STOQS_VOLS_DIR}/maps:/dev/shm
      - ${STOQS_VOLS_DIR}/stoqs_root:/root
      - ${STOQS_VOLS_DIR}/nginx:/usr/share/nginx
      - ${STOQS_VOLS_DIR}/pg_dumps:/srv/media-files/pg_dumps
      - ${STOQS_HOME}:/srv
      - static-files:/srv/static-files
      - media-files:/srv/media-files
    environment:
      - DATABASE_URL=postgis://${STOQSADM_USER}:${STOQSADM_PASSWORD}@${STOQS_PGHOST}:${STOQS_PGHOST_PORT}/stoqs
      - DATABASE_SUPERUSER_URL=postgis://postgres:${POSTGRES_PASSWORD}@${STOQS_PGHOST}:${STOQS_PGHOST_PORT}/stoqs
      - PGHOST=${STOQS_PGHOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAPSERVER_HOST=${MAPSERV_SERVER_NAME}
      - URL_MAPFILE_DIR=/maps
      - STATIC_URL=/static/
      - STATIC_ROOT=/srv/static-files
      - MEDIA_URL=/media/
      - MEDIA_ROOT=/srv/media-files
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - USER=${USER}
    container_name: stoqs
    depends_on:
      - mapserver
      - postgis
    # Expose port 8000 if PRODUCTION=false
    ##ports:
    ##  - "8000:8000"
    env_file:
      - ./.env

  # Disable nginx service if PRODUCTION=false
  nginx:
    image: mbari/stoqs-nginx
    build:
        context: .
        dockerfile: Dockerfile-nginx
    volumes:
      - ${STOQS_VOLS_DIR}/html:/srv/html
      - ${STOQS_VOLS_DIR}/pg_dumps:/srv/media-files/pg_dumps
      - static-files:/srv/static-files
      - media-files:/srv/media-files
    environment:
      - NGINX_TMPL=${NGINX_TMPL}
    container_name: stoqs-nginx
    ports:
      - "80:80"
      - "8000:8000"
      - "443:443"
    depends_on:
      - stoqs
    env_file:
      - ./.env

